# Generated by Django 6.0.3 on 2026-03-19 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_providerrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerrating',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerrating',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerrating',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='providerrating',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('inappropriate', 'Inappropriate Content'), ('fraud', 'Suspected Fraud'), ('duplicate', 'Duplicate Submission'), ('off_topic', 'Off-Topic'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='recoveryprovider',
            name='avg_response_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='recoveryprovider',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recoveryprovider',
            name='service_type',
            field=models.CharField(choices=[('towing', 'Towing'), ('salvage', 'Salvage'), ('medical', 'Medical'), ('fire', 'Fire Fighting'), ('fuel', 'Fuel Delivery'), ('general', 'General Recovery')], default='general', max_length=20),
        ),
    ]
