# Generated by Django 6.0.3 on 2026-03-19 07:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0002_statusupdate'),
        ('providers', '0003_providerrating_moderated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='assigned_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emergencies', to='providers.recoveryprovider'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='last_status_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='reported', max_length=20),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_emergencies', to=settings.AUTH_USER_MODEL),
        ),
    ]
