# Generated by Django 6.0.3 on 2026-03-15 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imo_number', models.CharField(max_length=20, unique=True)),
                ('vessel_type', models.CharField(choices=[('cargo', 'Cargo Ship'), ('tanker', 'Tanker'), ('passenger', 'Passenger Ship'), ('fishing', 'Fishing Vessel'), ('tug', 'Tug Boat'), ('other', 'Other')], max_length=20)),
                ('flag', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
