# Generated by Django 6.0.3 on 2026-03-23 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='call_sign',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vessel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='mmsi',
            field=models.CharField(blank=True, max_length=20, verbose_name='MMSI'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='ssr_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='SSR Number'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_type',
            field=models.CharField(choices=[('sailing', 'Sailing Yacht'), ('motor', 'Motor Yacht'), ('catamaran', 'Catamaran'), ('rib', 'RIB / Inflatable'), ('cargo', 'Cargo Ship'), ('tanker', 'Tanker'), ('passenger', 'Passenger Ship'), ('fishing', 'Fishing Vessel'), ('tug', 'Tug Boat'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('pre_passage', 'Pre-Passage Safety Check'), ('annual', 'Annual Service'), ('engine', 'Engine Service'), ('rigging', 'Rigging Inspection'), ('electrical', 'Electrical Systems'), ('hull', 'Hull Inspection'), ('safety_equipment', 'Safety Equipment Check'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(help_text='Describe what needs checking or any known issues')),
                ('requested_date', models.DateField(help_text='When do you need this completed by?')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('assigned_contractor', models.CharField(blank=True, max_length=100)),
                ('contractor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='vessels.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='PassagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Cowes to Cherbourg', max_length=100)),
                ('departure_port', models.CharField(max_length=100)),
                ('destination_port', models.CharField(max_length=100)),
                ('departure_datetime', models.DateTimeField()),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('route_description', models.TextField(help_text='Waypoints, headings, distances')),
                ('hazards', models.TextField(blank=True, help_text='Rocks, shoals, traffic separation schemes')),
                ('alternate_ports', models.TextField(blank=True, help_text='Ports of refuge along the route')),
                ('vhf_channels', models.CharField(blank=True, help_text='e.g. Ch16, Ch67, Ch80', max_length=100)),
                ('tidal_notes', models.TextField(blank=True, help_text='Tidal windows, heights, streams')),
                ('current_notes', models.TextField(blank=True)),
                ('crew_list', models.TextField(blank=True, help_text='Names and roles of all persons on board')),
                ('persons_on_board', models.PositiveIntegerField(default=1)),
                ('check_bilge', models.BooleanField(default=False, verbose_name='Bilge checked')),
                ('check_engine_bilge', models.BooleanField(default=False, verbose_name='Engine bilge checked')),
                ('check_oil_level', models.BooleanField(default=False, verbose_name='Oil level checked')),
                ('check_coolant', models.BooleanField(default=False, verbose_name='Coolant level checked')),
                ('check_transmission', models.BooleanField(default=False, verbose_name='Transmission belt checked')),
                ('engine_battery_v', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Engine battery (V)')),
                ('service_battery_v', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Service battery (V)')),
                ('fuel_level_pct', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fuel level (%)')),
                ('water_fwd_pct', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fwd water tank (%)')),
                ('water_aft_pct', models.PositiveIntegerField(blank=True, null=True, verbose_name='Aft water tank (%)')),
                ('engine_hours_start', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('engine_hours_end', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('weather_forecast', models.TextField(blank=True)),
                ('sea_state', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage_plans', to='vessels.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='VesselDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('insurance', 'Insurance Certificate'), ('registration', 'Registration / SSR Certificate'), ('safety', 'Safety Equipment Checklist'), ('passage_plan', 'Passage Plan / Float Plan'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='vessel_documents/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vessels.vessel')),
            ],
        ),
    ]
